<?php echo $this->doctype(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="EN" lang="EN" dir="ltr">
<head profile="http://gmpg.org/xfn/11">
<title>Golden compass english class</title>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="imagetoolbar" content="no" />
    
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/layout.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/code.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/forms.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/docs.min.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/templatemo_style.css');?>
    
    <?php echo $this->headTitle();?>
    <?php echo $this ->headMeta();?>
    <?php $md = "/work/public/modal/js/"; ?>
    <?php $js = "/work/public/js/"; ?>
    
    <!--<script type='text/javascript' src="https://gist.github.com/makeusabrew/6327194.js"></script>-->
    <script type='text/javascript' src='<?php echo $js;?>countdown.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>countdown.min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>jquery.min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>jquery.scrollTo-min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>jquery.localscroll-min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>bootstrap-tooltip.js'></script>

    <script src="<?php echo $js; ?>jquery.js"></script> 

    <script src="/work/public/bootstrap/js/bootstrap.min.js"></script>
    <link rel="icon" type="image/png" href="/work/public/images/icon.png" />
    <link href="/work/public/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/work/public/bootstrap/css/docs.min.css" rel="stylesheet">
    <link href="/work/public/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
    <script type='text/javascript' src='<?php echo $md;?>bootstrap-modal.js'></script>
    
    <?php $editor = '/work/public/ckeditor'; ?>
    <script type="text/javascript" src="<?php echo $editor; ?>/ckeditor.js"></script>
    <script type="text/javascript" src="<?php echo $editor; ?>/adapters/jquery.js"></script>
    <script type="text/javascript">
     $(function() {
                $('#textcontent' ).ckeditor();
            });
     var baseUrl = "http://localhost/work/public";
    </script>

</head>
<body id = "top">
<div class = "dis10"></div>
<div class = "body_header">
<div class = "left_dis">

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/index/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Нүүр хуудас</span></div></div></a></div></div>

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/bukhchuud/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Бидний тухай</span></div></div></a></div></div>

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/barildaan/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Сургалтууд</span></div></div></a></div></div>

<?php
          /*                  Хэрэглэгч нэвтрсэн үед             */
          if (Zend_Auth :: getInstance()->hasIdentity()) 
          {
              echo '<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/fantasy/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Фантази</span></div></div></a></div></div>';
          }
?>

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/other/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Санал Хүсэлт</span></div></div></a></div></div>

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/other/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Холбоо барих</span></div></div></a></div></div>

<div class = "right_dis">
<?php
          /*                  Хэрэглэгч нэвтрсэн үед             */
          if (Zend_Auth :: getInstance()->hasIdentity()) 
          {
              $uid = Zend_Registry::get('uid');
              echo '<div class = "user_loc"><ul>
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <img class="img" src="'.$this -> baseUrl().'/images/profile/adya.jpg" alt="" height = "28px" width = "28px"/>
                        
                      </a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="/work/public/user/mypage/id/'.$uid.'">Миний хуудас</a></li>
                        <li><a href="#">Хувийн тохиргоо</a></li>
                        <li><a href="#">Үзүүлэлт</a></li>
                        <li><a href="/work/public/authentication/logout">Гарах</a></li>
                      </ul>
                    </li>
                  </ul></div>';
          }
          else
          {
              echo '
              <div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/authentication/login"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Нэвтрэх</span></div></div></a></div></div>

              <div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/work/public/authentication/register"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Бүртгүүлэх</span></div></div></a></div></div>';
          }
?>
</div>
</div>  
</div>

<div class = "dis10"></div>
<div class="bodyHHH">
        <?php echo '<img src="'.$this -> baseUrl().'/images/banner.jpg" height="100%" width="100%"></img>'; ?> 
</div>
<div class="bodyHH">
  <div class="dis10"></div>
  <?php echo $this->layout()->content; ?> 
</div>
<div class="dis10"></div>
<div class="center">Монгол контент хөгжүүлэгч @ 2015</div>
<div class="dis10"></div>
</body>
</html>